### ISSUE TITLE
Transition to HTML5

### ISSUE THREAD

**Issue by fuerbringer** [GianlucaScarciolla/gianlucascarciolla.github.io#1]
Suggestion: Use HTML5 Tags and Doctypes instead of the decade old HTML4 Tags.
`<meta stuff="abc" />` becomes `<meta stuff=abc">`
`<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01>` becomes `<!DOCTYPE html>`
and so on.

**Comment by GianlucaScarciolla** [comment]
already done, but thanks!
